name: Rebase base branch onto PR

on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  handle-rebase-command:
    if: |
      github.event.issue.pull_request != null &&
      startsWith(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.issue.pull_request.head.ref }}

      - name: Get PR base ref
        id: pr_info
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            require('fs').appendFileSync(process.env.GITHUB_OUTPUT, `base_ref=${pr.data.base.ref}\n`);

      - name: Perform rebase
        id: rebase
        continue-on-error: true
        uses: peter-evans/rebase@v3
        with:
          head: ${{ github.event.issue.pull_request.head.label }}
          base: ${{ github.event.issue.pull_request.base.label }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post rebase success comment
        if: steps.rebase.outcome == 'success' && steps.rebase.outputs.rebased-count == '1'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.issue.number }}
          message: |
            ✅ **Rebase completed successfully!**
            This branch is now up to date with `${{ steps.pr_info.outputs.base_ref }}`

      - name: Post no rebase comment (up-to-date or conflict)
        if: steps.rebase.outcome == 'success' && steps.rebase.outputs.rebased-count == '0'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.issue.number }}
          message: |
            🤷 **No rebase was performed**
            This branch is either up-to-date or has merge conflicts preventing rebase.

            If your PR appears unchanged, it may have unresolved conflicts.
            Please check and resolve them manually if necessary.

      - name: Post rebase failure comment
        if: steps.rebase.outcome == 'failure'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.issue.number }}
          message: |
            ❌ **Rebase failed**
            Please resolve merge conflicts manually.

            [🔍 View Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
